version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ../data/mongo:/data/db
    ports:
      - "27017:27017"
  server:
    hostname: retail-group-news
    container_name: rgn-server
    image: rickydunlop/nodejs-ffmpeg
    restart: always
    build: .
    volumes:
    - .:/usr/src/app
    - npm-cache:/root/.npm
    command: npm run install-start
    ports:
    - "3000:3000"
    links:
    - mongo
    depends_on:
    - mongo

volumes:
  npm-cache:
    external: false